### ISSUE TITLE
Error in JSON unexpected token

### ISSUE THREAD

**Issue by yoshutch** [byu-oit/github-action-teams#11] opened 2022-02-11 18:54 UTC
After merging a PR to my dev branch this action failed in my [deploy workflow](https://github.com/byu-oit/ee-ces-api/runs/5160745037?check_suite_focus=true) 

```
Warning: Missing job parameter will result in reduced functionality.
Warning: Missing steps parameter will result in reduced functionality.
Warning: Missing needs parameter will result in reduced functionality.
Parsed params:
{"webhook_url":"***","job":{},"steps":{},"needs":{},"raw":"{\n  \"@type\": \"MessageCard\",\n  \"@context\": \"[https://schema.org/extensions\](https://schema.org/extensions/)",\n  \"summary\": \"success\",\n  \"themeColor\": \"4F7942\",\n  \"title\": \"The deploy workflow on byu-oit/ee-ces-api/@dev was a success\",\n  \"sections\": [\n    {\n      \"activityTitle\": \"Merge pull request #589 from byu-oit/cleanup\n\nchore: use prd branch and removed repo-meta\",\n      \"activitySubtitle\": \"2022-02-11T11:42:49-07:00\",\n      \"activityImage\": \"[https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/success.png\](https://raw.githubusercontent.com/Skitionek/notify-microsoft-teams/master/icons/success.png/)",\n      \"facts\": [\n        {\n          \"name\": \"Repository:\",\n          \"value\": \"[byu-oit/ee-ces-api]([https://github.com/byu-oit/ee-ces-api)\](https://github.com/byu-oit/ee-ces-api)/)"\n        },\n        {\n          \"name\": \"Commit:\",\n          \"value\": \"[35ebde628de71090aa72301e75909f2ebc805bd6]([https://github.com/byu-oit/ee-ces-api/commit/35ebde628de71090aa72301e75909f2ebc805bd6)\](https://github.com/byu-oit/ee-ces-api/commit/35ebde628de71090aa72301e75909f2ebc805bd6)/)"\n        },\n        {\n          \"name\": \"Triggered by:\",\n          \"value\": \"[ yoshutch ]([https://github.com/yoshutch)\](https://github.com/yoshutch)/)"\n        }\n      ]\n    }\n  ],\n  \"potentialAction\": [\n    {\n      \"@type\": \"OpenUri\",\n      \"name\": \"View Actions\",\n      \"targets\": [\n        {\n          \"os\": \"default\",\n          \"uri\": \"[https://github.com/byu-oit/ee-ces-api/actions\](https://github.com/byu-oit/ee-ces-api/actions/)"\n        }\n      ]\n    },\n    {\n      \"@type\": \"OpenUri\",\n      \"name\": \"View Repo\",\n      \"targets\": [\n        {\n          \"os\": \"default\",\n          \"uri\": \"[https://github.com/byu-oit/ee-ces-api\](https://github.com/byu-oit/ee-ces-api/)"\n        }\n      ]\n    }\n  ]\n}","overwrite":"","dry_run":""}
Error: Unexpected token 
 in JSON at position 290
```

For some reason pushing directly to dev works just fine, but merging a PR fails.

**Comment by stuft2** [comment] 2022-02-11 21:26
Duplicate of https://github.com/byu-oit/github-action-teams/issues/9

**Comment by GaryGSC** [comment] 2022-11-01 20:38
Should be resolved in [v3](https://github.com/byu-oit/github-action-teams/releases/tag/v3.0.0).

**Closed as completed by GaryGSC** 2022-11-01 20:38 UTC
